// 主要銘柄の ticker → domain マッピング（Clearbit Logo API 用）
// カバレッジ: SP500 主要 + メガキャップ + 主要 ETF + 注目グロース
// 未掲載銘柄は CompanyLogo 側でグラデーション円フォールバック

export const TICKER_DOMAINS = {
  // ── メガキャップ ───────────────────────────────
  AAPL: 'apple.com',
  MSFT: 'microsoft.com',
  GOOGL: 'abc.xyz',
  GOOG: 'abc.xyz',
  AMZN: 'amazon.com',
  META: 'meta.com',
  NVDA: 'nvidia.com',
  TSLA: 'tesla.com',
  BRK_B: 'berkshirehathaway.com',
  AVGO: 'broadcom.com',

  // ── 半導体 ─────────────────────────────────────
  AMD: 'amd.com',
  INTC: 'intel.com',
  TSM: 'tsmc.com',
  ASML: 'asml.com',
  QCOM: 'qualcomm.com',
  TXN: 'ti.com',
  MU: 'micron.com',
  AMAT: 'appliedmaterials.com',
  LRCX: 'lamresearch.com',
  KLAC: 'kla.com',
  ARM: 'arm.com',
  ON: 'onsemi.com',
  MRVL: 'marvell.com',
  ADI: 'analog.com',
  MCHP: 'microchip.com',
  NXPI: 'nxp.com',
  STM: 'st.com',

  // ── 金融 ───────────────────────────────────────
  JPM: 'jpmorganchase.com',
  BAC: 'bankofamerica.com',
  WFC: 'wellsfargo.com',
  C: 'citigroup.com',
  GS: 'goldmansachs.com',
  MS: 'morganstanley.com',
  BLK: 'blackrock.com',
  AXP: 'americanexpress.com',
  V: 'visa.com',
  MA: 'mastercard.com',
  PYPL: 'paypal.com',
  SCHW: 'schwab.com',
  USB: 'usbank.com',
  PNC: 'pnc.com',
  COF: 'capitalone.com',
  TFC: 'truist.com',

  // ── ヘルスケア ─────────────────────────────────
  UNH: 'unitedhealthgroup.com',
  JNJ: 'jnj.com',
  LLY: 'lilly.com',
  PFE: 'pfizer.com',
  MRK: 'merck.com',
  ABBV: 'abbvie.com',
  TMO: 'thermofisher.com',
  ABT: 'abbott.com',
  DHR: 'danaher.com',
  BMY: 'bms.com',
  AMGN: 'amgen.com',
  GILD: 'gilead.com',
  CVS: 'cvshealth.com',
  ELV: 'elevancehealth.com',
  ISRG: 'intuitivesurgical.com',
  REGN: 'regeneron.com',
  VRTX: 'vrtx.com',
  MDT: 'medtronic.com',
  SYK: 'stryker.com',
  BSX: 'bostonscientific.com',
  ZTS: 'zoetis.com',
  HUM: 'humana.com',
  CI: 'cigna.com',

  // ── 消費財・小売 ───────────────────────────────
  WMT: 'walmart.com',
  COST: 'costco.com',
  HD: 'homedepot.com',
  LOW: 'lowes.com',
  TGT: 'target.com',
  PG: 'pg.com',
  KO: 'coca-colacompany.com',
  PEP: 'pepsico.com',
  MCD: 'mcdonalds.com',
  SBUX: 'starbucks.com',
  NKE: 'nike.com',
  DIS: 'thewaltdisneycompany.com',
  CMCSA: 'comcastcorporation.com',
  NFLX: 'netflix.com',
  EBAY: 'ebay.com',
  ETSY: 'etsy.com',
  ABNB: 'airbnb.com',
  BKNG: 'booking.com',
  MAR: 'marriott.com',
  HLT: 'hilton.com',
  CMG: 'chipotle.com',
  YUM: 'yum.com',
  DPZ: 'dominos.com',
  LULU: 'lululemon.com',

  // ── テック・ソフトウェア ───────────────────────
  ORCL: 'oracle.com',
  CRM: 'salesforce.com',
  ADBE: 'adobe.com',
  NOW: 'servicenow.com',
  IBM: 'ibm.com',
  CSCO: 'cisco.com',
  INTU: 'intuit.com',
  PANW: 'paloaltonetworks.com',
  SNOW: 'snowflake.com',
  PLTR: 'palantir.com',
  CRWD: 'crowdstrike.com',
  NET: 'cloudflare.com',
  DDOG: 'datadoghq.com',
  ZS: 'zscaler.com',
  MDB: 'mongodb.com',
  TEAM: 'atlassian.com',
  WDAY: 'workday.com',
  HUBS: 'hubspot.com',
  DOCU: 'docusign.com',
  ZM: 'zoom.us',
  OKTA: 'okta.com',
  TWLO: 'twilio.com',
  SHOP: 'shopify.com',
  SQ: 'block.xyz',
  COIN: 'coinbase.com',
  RBLX: 'roblox.com',
  U: 'unity.com',
  DASH: 'doordash.com',
  UBER: 'uber.com',
  LYFT: 'lyft.com',
  PINS: 'pinterest.com',
  SNAP: 'snap.com',
  SPOT: 'spotify.com',
  ROKU: 'roku.com',

  // ── 通信・メディア ─────────────────────────────
  T: 'att.com',
  VZ: 'verizon.com',
  TMUS: 'T-Mobile.com',
  CHTR: 'charter.com',
  WBD: 'wbd.com',
  PARA: 'paramount.com',

  // ── エネルギー ─────────────────────────────────
  XOM: 'exxonmobil.com',
  CVX: 'chevron.com',
  COP: 'conocophillips.com',
  SLB: 'slb.com',
  EOG: 'eogresources.com',
  PSX: 'phillips66.com',
  MPC: 'marathonpetroleum.com',
  OXY: 'oxy.com',
  HAL: 'halliburton.com',

  // ── 産業・運輸 ─────────────────────────────────
  CAT: 'caterpillar.com',
  DE: 'deere.com',
  BA: 'boeing.com',
  HON: 'honeywell.com',
  GE: 'ge.com',
  RTX: 'rtx.com',
  LMT: 'lockheedmartin.com',
  UPS: 'ups.com',
  FDX: 'fedex.com',
  UNP: 'up.com',
  CSX: 'csx.com',
  NSC: 'norfolksouthern.com',
  DAL: 'delta.com',
  UAL: 'united.com',
  AAL: 'aa.com',
  LUV: 'southwest.com',

  // ── 素材・REIT ─────────────────────────────────
  LIN: 'linde.com',
  APD: 'airproducts.com',
  ECL: 'ecolab.com',
  AMT: 'americantower.com',
  PLD: 'prologis.com',
  EQIX: 'equinix.com',
  CCI: 'crowncastle.com',
  PSA: 'publicstorage.com',

  // ── 中国・ADR ──────────────────────────────────
  BABA: 'alibaba.com',
  PDD: 'pddholdings.com',
  JD: 'jd.com',
  BIDU: 'baidu.com',
  NIO: 'nio.com',
  XPEV: 'xpeng.com',
  LI: 'lixiang.com',

  // ── 日本 ADR ───────────────────────────────────
  TM: 'toyota.com',
  SONY: 'sony.com',
  HMC: 'honda.com',
  MUFG: 'mufg.jp',

  // ── 主要 ETF ───────────────────────────────────
  SPY: 'spdrs.com',
  VOO: 'vanguard.com',
  VTI: 'vanguard.com',
  QQQ: 'invesco.com',
  DIA: 'spdrs.com',
  IWM: 'ishares.com',
  EEM: 'ishares.com',
  GLD: 'spdrs.com',
  SLV: 'ishares.com',
  USO: 'uscfinvestments.com',
  TLT: 'ishares.com',
  HYG: 'ishares.com',
  XLK: 'spdrs.com',
  XLF: 'spdrs.com',
  XLE: 'spdrs.com',
  XLV: 'spdrs.com',
  XLY: 'spdrs.com',
  XLP: 'spdrs.com',
  XLI: 'spdrs.com',
  XLB: 'spdrs.com',
  XLU: 'spdrs.com',
  XLRE: 'spdrs.com',
  XLC: 'spdrs.com',
  ITA: 'ishares.com',
  ARKK: 'ark-invests.com',
  SOXX: 'ishares.com',
  SMH: 'vaneck.com',

  // ── 注目グロース ──────────────────────────────
  AVGO_alt: 'broadcom.com',
  MELI: 'mercadolibre.com',
  TTD: 'thetradedesk.com',
  CDNS: 'cadence.com',
  SNPS: 'synopsys.com',
  FTNT: 'fortinet.com',
  ANET: 'arista.com',
  KLA: 'kla.com',
};

// ティッカー（"BRK.B" 等のドット入り）正規化キー
function normalize(ticker) {
  if (!ticker) return '';
  return ticker.toUpperCase().replace(/[.\-]/g, '_');
}

export function getTickerDomain(ticker) {
  return TICKER_DOMAINS[normalize(ticker)] || null;
}
